### ISSUE TITLE
Youtube チャンネルのリンクを追加

### ISSUE THREAD

**Issue by hirofumii** [ginowanhumanstage/www.humanstage.net#21]
## 問題

山田さんが [Youtube チャンネルを開設している](https://www.youtube.com/channel/UCkGHTZ4duRmOcwclouDiDKg/featured) ので、そのリンクをサイトにも設置したい。

## 解決策

- Webサイトのヘッダーの SNS ボタンへ Youtube を追加し、リンクを設置。
- 現在このような状況でライブの開催できておらず、積極的に動画を上げているようなので、いっそ再生リストとかを TOP に埋め込めるとなおいいかもしれない。

**Comment by hirofumii** [comment]
大変残念ながら閉店とのことで・・・別の形の対応を検討。

**Comment by yuta-nihei** [comment]
承知しました!
