### ISSUE TITLE
今後のヒューマンステージについて

### ISSUE THREAD

**Issue by hirofumii** [ginowanhumanstage/www.humanstage.net#26]
今月22日に山田さんと今後についてのミーティング実施。

## 議事録とTODO

- ライブハウスとしてのヒューマンステージは閉店
  - いつかまたやりたいが、今はできない
  - よって下記の、ライブハウスの情報を消す
    - [x] アクセスページを消す
    - [x] スケジュールページを消す
- 9月あたりに新事業を立ち上げる方向で進めている
- 現在クラウドファンディングにて資金を調達中
- それまではトップページを、「次があるよ…！」と期待させる感じにしたい
- 今トップにくると支援ページへのリンクが先に目が着て、閉店の事実を知らないと「なんで？」ってなりそう
  - [x] ツイッターへのリンクを、いっそツイート自体を埋め込む形へ変更
- ヒューマンステージのライブ動画も引き続きアーカイブスとして収集して公開していきたい
  - [ ] Youtube チャンネルへのリンクをもっとわかりやすくする (素材がとどいたら？)
- プロの人が撮ったヒューマンの写真がたくさんあり、どこかで展示会をしたい
  - 展示会終了後、Web サイト上へその写真のギャラリーページを作りたい
    - [ ] 技術選定をする。WordPress で登録させて、それをフロントでいい感じに表示できればオケ？
- アーティストとの対談記事のアップを、月イチくらいでやりたい
  - [ ] 記事を WordPress から投稿できるようにする
- 記事やギャラリーの管理は笑う月のチエさんが全面的に手伝ってくれそう
- 必要なバナー画像とかもチエさんが作ってくれそう (とてもありがたい！)
  - [ ] チエさんの WordPress アカウントを発行する
  - [ ] 記事のプレビューが行えないという問題を解決したい (フロントを Gatsby で行っているので…)

## 簡単にまとめると

とりあえず9月までに、不要な情報の削除と、トップを期待させる感じに整備する。
9月くらいには新事業の内容をアップする。
ギャラリーや対談記事はその先になる見込み。

**Comment by yuta-nihei** [comment]
議事録ありがとうございます!
記事のプレビュー機能の解決を行いたいですね。

**Comment by hirofumii** [comment]
そうなのよね～。

色々調べてみているんだけど、サイトのホスティングが今は Netlify だけど、Gatsby の開発元が提供している Gatsby cloud ってのに移行したら Live preview が簡単にできそう。

もしくは自前でやるんなら↓のような方法もありそう。(そこそこ大変そうだけど)
- [Live Previews with WordPress and Gatsby | Justin W. Hall](https://justinwhall.com/live-previews-with-wordpress-gatsby/)
- [Live Preview in Gatsby without the Cost | by Kevin Green | The Couch | Medium](https://medium.com/the-couch/live-preview-in-gatsby-without-the-cost-21f8ac0337bb)

Netlify はすごぶる便利なんだけど、[こんな記事](https://blog.anatoo.jp/2020-08-03)もあったりするので表示速度を重視するのであれば変更を検討しても良さそう。(確かにちょっと、もっさりしている感じはしていたのだが…)

とりあえずこの辺りは引き続き調査っていう感じで！

**Comment by yuta-nihei** [comment]
Gatsby Cloudに移行できそうであれば、移行したほうがいいかもですね!
Free版だと25回/1日しか、新規作成・編集が行えないみたいですが...

**Comment by hirofumii** [comment]
おお、ナイス調査！それは見落としてた…

ちょっと試用してみないとなんともいえないけど、[ここ](https://www.gatsbyjs.org/blog/2020-01-27-announcing-gatsby-builds-and-reports/#what-is-a-real-time-edit)読む感じリアルタイムプレビューが1日25回に制限されるっぽいねぇ。
結構厳しいが…、超えたらどうなるのかもちょっと確認しときたいね。

**Comment by yuta-nihei** [comment]
Gatsby CloudのQuestionにこう記載されてました。

「プレビューなど、すべての主要機能を利用できます。ただし、1日あたりのリアルタイム編集が25を超えると、プレビューインスタンスのライブアップデートにアクセスできなくなります。」

複数人が触る予定があるのであれば、Free版では難しいかもしれないですね...

**Comment by hirofumii** [comment]
なるほど、うーん厳しそうだね…。
1日にそれほどたくさん記事をアップする事はないと思うんだけど、慣れるまでは何回もプレビューしそうだしね。

一応試用はしてみたいけど、自前の線で検討かなぁ、ちょっと大変そうだけど。

**Comment by yuta-nihei** [comment]
そうですね...
自前がいいかもですね!

**Comment by hirofumii** [comment]
この issue はクローズし、それぞれ個別の issue で対応する形とします。
とりあえずプレビューの件は #29 を立てときました。
